### get submission
GET http://localhost:8080/submissionEnvelopes/5cdc1a0ad96dad0008593264/

> {%
client.global.set("projects", response.body._links.projects.href);
client.global.set("exportJobs", response.body._links.exportJobs.href);
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 202");
});
%}
### get project
GET {{projects}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 202");
});
client.global.set("project_uuid", response.body._embedded.projects[0].uuid.uuid); %}

### create export job
POST {{exportJobs}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJyc2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxNTNmOTA0ODU3YTg2YjY3ZGRiNjQ0OTIyYzUxZjJkNWYxYjZlMmVhQGVsaXhpci1ldXJvcGUub3JnIiwiYXpwIjoiZTIwNDFjMmQtOTQ0OS00NDY4LTg1NmUtZTg0NzExY2ViZDIxIiwic2NvcGUiOiJlbWFpbCBvcGVuaWQgcHJvZmlsZSIsImlzcyI6Imh0dHBzOi8vbG9naW4uZWxpeGlyLWN6ZWNoLm9yZy9vaWRjLyIsImV4cCI6MTY2NjkxNzU4MCwiaWF0IjoxNjY2OTAzMTgwLCJqdGkiOiJhNmY4Y2I3Zi04ZTRkLTRiMzYtODllOC1lYWNkOGQ0N2JkNTEifQ.Dxh7n2kwHr6BZ9AOxyjYBOdq6_LmKm_DXy5zZq94N148BcLf4mbJiX2b48iSo6cenLTub1HFIr5Ec-cCXT2fXl4_wIJ8v8rNaT3ascgaA9HEWgcKX3jaD7xI7ob7nFKmZ-K7-q2MGCa2uNWfCI7cAAzBWcs-kF0LlEzg5THRXKxpHHqx-z8yUUvWTXD-f0Gwevy3Kf1pDJpYCaKg_MX793oAlYlZrkn33A4O2v7LqxzEV8ym3Uywl42RVW0Nx6lBljJMJvB_q1BCUA0zlU6p1e_KL6Hx_iS6avLKcsECGjWtcTT6xXfrwc2EUZqgkIELUlhXCvYCBdpUvf3WgRVt8A

{
  "destination": {
    "name": "Dcp",
    "context": {"projectUuid" : "{{project_uuid}}"}
  },
  "context": {}
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 202");
});
client.global.set("exportJob", response.body._links.exportJob.href);
%}


### start export spreadsheet
PATCH {{exportJob}}/context
Accept: application/json
Content-Type: application/json

{"dataFileTransfer": "COMPLETE"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}

